### ISSUE TITLE
Metadata Production Crops

### ISSUE THREAD

**Issue by UlrikeWood-Sichra** [FAOSTAT/faostat-ui#107]
Each item for which there are explanations can be expanded and collapsed.
Instead of writing 'EXPAND', and the text under the mouse becoming 'expand' or 'collapse' depending on where one is, it would be clearer to have arrows.
Text and the expand/collapse options could be written close together. It is really unclear after a while what is what.
Maybe you are still working on this.

**Comment by Kalimaha** [comment]
we are making the metadata more efficient and we are restyling it as per the attached picture

<img width="862" alt="schermata 2015-09-15 alle 09 52 43" src="https://cloud.githubusercontent.com/assets/1777311/9870827/92d34190-5b8f-11e5-9328-f8cfbc6f19d2.png">
